components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    URLItem:
      properties:
        url:
          title: Url
          type: string
      required:
      - url
      title: URLItem
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: API schema for the FastAPI Web Crawler Service
  title: FastAPI Web Crawler Service
  version: 0.1.0
openapi: 3.1.0
paths:
  /scrape/:
    get:
      operationId: export_openapi_schema_scrape__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Export Openapi Schema
    post:
      operationId: scrape_scrape__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/URLItem'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Scrape
