openapi: 3.0.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/scrape/":
    post:
      summary: Scrape
      operationId: scrape_scrape__post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/URLItem"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    URLItem:
      properties:
        url:
          type: string
          title: Url
      type: object
      required:
      - url
      title: URLItem
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
